In [4]:
import numpy as np 

def determinant(matrix , n): 
    if n == 1:
        return matrix[0][0]
    if n == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    det = 0
    for j in range(n):
        cofactor = []
        for row in range(1,n):
            temp = []
            for col in range(n):
                if col != j:
                    temp.append(matrix[row][col])
            cofactor.append(temp)
        det += (-1) ** j * matrix[0][j] * determinant(cofactor ,n-1)
    return det


برای سوال اول از ما خواسته شده بود تا دستگاه معمادلات را حل کنیم
برای حل معادله از طریق وارون ضرایب نیاز به تابع دترمینان هستیم که یک ماتریس ان در ان را محاسبه کند
 روش حل آن به شکل بازگشتی می‌باشد شروط پایه شامل اندازه ماتریس ۱ ، یا ۲ در ۲ بودن است به طوری که اگر یک در یک باشد خود عدد و دو در دو به صورت حل پایه ای آن دترمینان آن را حساب می‌کنیم.
برای محسابه دترمینان ماتریس های بزرگتر ابتدا با پیمایش روی سطر اول آن و حساب کردن کهاد متناظر با هر عضو سطر اول و ضرب آن در -۱ به توان جمع سطر و ستون آن را حساب میکنیم . درنهایت دترمینان ما مجموع ترم های گفته شده است. 

In [5]:

def cramer (coefficientsArray , constantsArray , n):
    result = np.zeros(n)
    for i in range (n):
        coefficientsArray_copy = coefficientsArray.copy()
        for j in range (n):
            coefficientsArray_copy[j][i] = constantsArray[j]
        result[i] = (determinant(coefficientsArray_copy , n)) / (determinant(coefficientsArray, n))
    return result 


تابع کرامر بدین شکل است که ابتدا یک کپی از ماتریس ضرایب را می‌سازد تا هنگام محاسبه مقادیر مختلف جواب ها با از دست رفتن اطلاعات مواجه نشویم. هر جواب ما حاصل از قرار دادن ثابت های معادله در ستون متناظر با شماره جواب است که حاصل تقسیم دترمینان ساخته شده بر دترمینان ماتریس ضرایب است که همیشه ثابت است

In [6]:


import numpy as np

def matrix_inverse(matrix , n):
    det = determinant(matrix , n)
    if det == 0:
        return "you can not inverse this matrix"

    inverse = np.zeros_like(matrix, dtype=float)
    adjugate = np.zeros_like(matrix, dtype=float)

    for i in range(n):
        for j in range(n):
            adjugate[j, i] = (-1) ** (i + j) * determinant(matrix[np.arange(n) != i][:, np.arange(n) != j] , n-1)
    
    inverse = adjugate / det
    return inverse


برای ادامه محاسبه از طریق وارون ضرایب نیاز به محاسبه این ماتریس هستیم در ابتدا درترمینان ماتریس ضرایب را محاسبه میکنیم اگر حاصل دترمینان بود می دانیم که ماتریس وارون پذیر نمی‌باشد و معادله جوابی ندارد.در غیراینصورت با محاسبه ماتریس الحاقی به شکلی که تمامی کهاد های اعضا ماتریس را حساب کرده و سپس ماتریس حاصل را ترانهاده کنیم بدست می‌اید و ماتریس حاصل را تقسیم بر قرینه وارون دترمینان ضرایب می‌کنیم سپس در ادامه تابع ضرایب را با ماتریس وارون ضرب میکنیم تا حاصل بدست آید.


In [9]:


def inverse_way(coefficientsArray , constantsArray , n):
    inverse = matrix_inverse(coefficientsArray , n)
    return np.dot(inverse, constantsArray)


numberOfVariables = int(input('Enter the number of variables: '))
coefficientsArray = np.zeros((numberOfVariables, numberOfVariables))
constantsArray = np.zeros(numberOfVariables)

for i in range (1,numberOfVariables+1):
    coefficients = list(map(int, input('Enter the coefficients of equation ' + str(i) + ' :').split()))
    for j in range (numberOfVariables) :
        coefficientsArray[i-1][j] = coefficients[j]
    constant = float(input('Enter the constant of equation ' + str(i) + ' :'))
    constantsArray[i-1] = constant

print(coefficientsArray)
print(constantsArray)
print("cramer " , cramer(coefficientsArray , constantsArray , numberOfVariables))
print("inverse way " ,inverse_way(coefficientsArray , constantsArray , numberOfVariables))

[[ 2.  4.  0.  8.]
 [-1.  3.  8.  2.]
 [ 3.  9.  5.  2.]
 [10.  7. 12.  5.]]
[22.  4. 14.  0.]
cramer  [-1.32835821  2.07462687 -0.95522388  2.04477612]
inverse way  [-1.32835821  2.07462687 -0.95522388  2.04477612]


  خروجی های سوال ۱ در عکس های قرار داده شد در فایل قابل مشاهده است که هر دو روش به جواب یکسان میرسند