In [4]:
import numpy as np

def rank(matrix , rows , cols):
    A = matrix.copy()
    rank = 0
    for i in range(rows):
        for j in range(cols):
            if A[i, j] != 0:
                rank += 1
                A[i] /= A[i, j]
                # print("here" , A)
                for k in range(i + 1, rows):
                    A[k] -= A[i] * A[k, j]
                print("here2" ,A)
                break
    return rank

rows = int(input("Enter the number of rows :"))
cols = int(input("Enter the number of cols :"))
matrix = np.zeros((rows,cols))
for i in range(rows):
    row = list(map(int, input().split()))
    matrix[i] = row

print("The rank of matrix is :",rank(matrix,rows,cols))


here2 [[ 1.   0.6  0.5  0.3]
 [ 0.   1.8  6.   5.4]
 [ 0.   4.2 -3.  -0.4]]
here2 [[  1.           0.6          0.5          0.3       ]
 [  0.           1.           3.33333333   3.        ]
 [  0.           0.         -17.         -13.        ]]
here2 [[ 1.          0.6         0.5         0.3       ]
 [ 0.          1.          3.33333333  3.        ]
 [-0.         -0.          1.          0.76470588]]
The rank of matrix is : 3


برای محسابه رنک یک ماتریس ابتدا ان را به فرم اچلون در می‌آوریم ( با عملگر های سطری ماتریس) سپس حاصل رنک ماتریس برابر است با تعداد سطر های غیرصفر. در ابتدا این تابع ماتریس ورودی را گرفته و بدین ترتیب عمل می کند در هر سطر ماتریس به دنبال اولین عدد غیر صفر می گردد در اون صورت چون این سطر قبلا توسط سطر های دیگر صفر نشده رنک را یکی زیاد میکند پس از نرمال سازی سطر مورد نظر که برابر است با تقسیم کل سطر بر اندازه اولین عدد غیر صفر سطر بدست می ‌آید سپس تمامی سطر های زیری را متناسب با جایگاه یک سطر اولیه اپدیت میکنیم بدین شکل که عضوی که زیر عدد یک سطر اولیه وجود دارد توسط عملگر های سطری به صفر تبدیل شود و طبعا مقدار بقیه سطر همزمان با این عملکرد اپدیت شود. در نهایت با خروجی دادن مقدار رنک به خواسته سوال می‌رسیم.


برای فهم بهتر اتفاقات گفته شده داخل تابع رنک دو پرینت قرار داده شده که نحوه عملیات های سطری را برای تبدیل به فرم اچلون در خروجی نمایش می‌دهد.
